import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '@/auth/useAuth'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { deleteMemory, getMemory, updateMemory } from '../api/client'

export function MemoryEditPage() { const { memoryId = '' } = useParams(); const navigate = useNavigate(); const { request } = useAuth(); const [value, setValue] = useState(''); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); useEffect(() => { void getMemory(request, memoryId).then((memory) => setValue(memory.canonical_text)).catch(() => setError('无法加载这条记忆。')) }, [memoryId, request]); async function save() { setSaving(true); try { await updateMemory(request, memoryId, value); navigate('/app/me/memories', { replace: true }) } catch { setError('保存失败，请重试。') } finally { setSaving(false) } } async function remove() { setSaving(true); try { await deleteMemory(request, memoryId); navigate('/app/me/memories', { replace: true }) } catch { setError('删除失败，请重试。') } finally { setSaving(false); setOpen(false) } } return <section className="space-y-4"><div><p className="text-sm text-muted-foreground">保存后来源会显示为“用户手动维护”。</p></div><div className="space-y-2 rounded-xl border border-border bg-card p-4 shadow-sm"><Label htmlFor="memory-text">偏好内容</Label><Input className="h-11" id="memory-text" onChange={(event) => setValue(event.target.value)} value={value} /></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}<Button className="h-11 w-full" disabled={!value.trim() || saving} onClick={() => void save()} type="button">{saving ? '正在保存…' : '保存修改'}</Button><Button className="h-11 w-full" disabled={saving} onClick={() => setOpen(true)} type="button" variant="destructive">删除这条记忆</Button><AlertDialog onOpenChange={setOpen} open={open}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这条记忆？</AlertDialogTitle><AlertDialogDescription>删除后，后续建议不会再参考它。此操作无法撤销。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={() => void remove()} variant="destructive">确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section> }
