"""Generate and validate the repository's Python 3.11 hash-complete lock file."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any


DIRECT_PREFIX = "# direct-dependency: "
LOCK_HEADER = "# Generated by lock_dependencies.py for Python 3.11; do not edit."
PIN_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9_.-]*)(?P<extras>\[[A-Za-z0-9_,.-]+\])?==(?P<version>[^\s;]+)$"
)
LOCK_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9_.-]*)==(?P<version>[^\s]+)(?P<hashes>(?:\s+--hash=sha256:[a-f0-9]{64})+)$"
)


class LockValidationError(ValueError):
    """The lock cannot safely reconstruct the declared project dependencies."""


def _normalized_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _parse_requirement(requirement: str) -> tuple[str, str, str]:
    match = PIN_RE.fullmatch(requirement)
    if match is None:
        raise LockValidationError(
            f"direct dependency must be exactly pinned as name[extra]==version: {requirement}"
        )
    name = match.group("name")
    return _normalized_name(name), match.group("version"), requirement


def direct_dependencies(pyproject_path: Path) -> list[str]:
    try:
        project = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise LockValidationError(f"cannot read {pyproject_path}: {error}") from error
    metadata = project.get("project")
    if not isinstance(metadata, dict):
        raise LockValidationError("pyproject is missing [project]")
    dependencies = metadata.get("dependencies", [])
    extras = metadata.get("optional-dependencies", {})
    dev_dependencies = extras.get("dev", []) if isinstance(extras, dict) else []
    if not isinstance(dependencies, list) or not isinstance(dev_dependencies, list):
        raise LockValidationError("project dependencies and dev extra must be arrays")
    direct = [*dependencies, *dev_dependencies]
    if not all(isinstance(item, str) for item in direct):
        raise LockValidationError("direct dependency entries must be strings")
    parsed = [_parse_requirement(item) for item in direct]
    normalized = [name for name, _, _ in parsed]
    if len(set(normalized)) != len(normalized):
        raise LockValidationError("a direct dependency is declared more than once")
    return sorted(item for _, _, item in parsed)


def runtime_dependencies(pyproject_path: Path) -> list[str]:
    """Return only production direct dependencies; dev extras never enter runtime exports."""

    try:
        project = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise LockValidationError(f"cannot read {pyproject_path}: {error}") from error
    metadata = project.get("project")
    dependencies = metadata.get("dependencies", []) if isinstance(metadata, dict) else []
    if not isinstance(dependencies, list) or not all(isinstance(item, str) for item in dependencies):
        raise LockValidationError("project dependencies must be an array of strings")
    parsed = [_parse_requirement(item) for item in dependencies]
    names = [name for name, _, _ in parsed]
    if len(names) != len(set(names)):
        raise LockValidationError("a runtime dependency is declared more than once")
    return sorted(item for _, _, item in parsed)


def _read_lock(lock_path: Path) -> tuple[list[str], dict[str, tuple[str, set[str]]]]:
    try:
        lines = lock_path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise LockValidationError(f"cannot read {lock_path}: {error}") from error
    if not lines or lines[0] != LOCK_HEADER:
        raise LockValidationError("requirements.lock has no recognized generated header")
    direct: list[str] = []
    pins: dict[str, tuple[str, set[str]]] = {}
    for line in lines[1:]:
        if not line:
            continue
        if line.startswith(DIRECT_PREFIX):
            direct.append(line.removeprefix(DIRECT_PREFIX))
            continue
        if line.startswith("#"):
            continue
        match = LOCK_RE.fullmatch(line)
        if match is None:
            raise LockValidationError(
                f"invalid or SHA-256-hash-incomplete lock entry: {line}"
            )
        normalized = _normalized_name(match.group("name"))
        hashes = set(re.findall(r"--hash=sha256:([a-f0-9]{64})", match.group("hashes")))
        if not hashes:
            raise LockValidationError(f"{match.group('name')} has no SHA-256 hash")
        if normalized in pins:
            raise LockValidationError(f"duplicate lock entry for {match.group('name')}")
        pins[normalized] = (match.group("version"), hashes)
    return direct, pins


def check_lock(pyproject_path: Path, lock_path: Path) -> None:
    """Verify exact direct dependency coverage, stable pins, and all artifact hashes."""

    expected_direct = direct_dependencies(pyproject_path)
    actual_direct, pins = _read_lock(lock_path)
    if actual_direct != expected_direct:
        raise LockValidationError(
            "pyproject drift: lock direct-dependency headers do not exactly match pyproject"
        )
    for requirement in expected_direct:
        normalized, version, _ = _parse_requirement(requirement)
        resolved = pins.get(normalized)
        if resolved is None:
            raise LockValidationError(f"direct dependency is missing from lock: {requirement}")
        if resolved[0] != version:
            raise LockValidationError(
                f"direct dependency version mismatch for {requirement}: lock has {resolved[0]}"
            )
    if not pins:
        raise LockValidationError("requirements.lock contains no pinned artifacts")


def _run(command: list[str], *, cwd: Path) -> None:
    completed = subprocess.run(command, cwd=cwd, text=True, capture_output=True, check=False)
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip()
        raise LockValidationError(f"pip command failed ({' '.join(command)}): {detail}")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as artifact:
        for chunk in iter(lambda: artifact.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _report_packages(report: dict[str, Any]) -> dict[str, tuple[str, str, str]]:
    packages: dict[str, tuple[str, str, str]] = {}
    installs = report.get("install")
    if not isinstance(installs, list):
        raise LockValidationError("pip report has no install list")
    for record in installs:
        if not isinstance(record, dict):
            raise LockValidationError("pip report contains an invalid install record")
        metadata = record.get("metadata")
        download = record.get("download_info")
        if not isinstance(metadata, dict) or not isinstance(download, dict):
            continue  # The local project itself is not a distributable dependency artifact.
        source_url = download.get("url")
        if isinstance(source_url, str) and source_url.startswith("file://"):
            continue  # The local project is installed separately; requirements.lock pins only indexes.
        name, version = metadata.get("name"), metadata.get("version")
        archive = download.get("archive_info")
        if not isinstance(name, str) or not isinstance(version, str) or not isinstance(archive, dict):
            raise LockValidationError("pip report is missing package metadata or archive information")
        report_hash = archive.get("hash")
        if not isinstance(report_hash, str) or not report_hash.startswith("sha256="):
            raise LockValidationError(f"pip report has no SHA-256 archive hash for {name}")
        normalized = _normalized_name(name)
        if normalized in packages:
            raise LockValidationError(f"pip report resolved {name} more than once")
        packages[normalized] = (name, version, report_hash.removeprefix("sha256="))
    if not packages:
        raise LockValidationError("pip report resolved no external packages")
    return packages


def generate_lock(pyproject_path: Path, lock_path: Path) -> None:
    """Resolve exact project and dev dependencies, download artifacts, then write hashes."""

    direct = direct_dependencies(pyproject_path)
    project_dir = pyproject_path.parent
    with tempfile.TemporaryDirectory(prefix="food-agent-lock-") as temporary:
        temp_dir = Path(temporary)
        report_path = temp_dir / "resolution.json"
        _run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--dry-run",
                "--ignore-installed",
                "--report",
                str(report_path),
                ".[dev]",
            ],
            cwd=project_dir,
        )
        try:
            report = json.loads(report_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise LockValidationError(f"cannot parse pip resolution report: {error}") from error
        if not isinstance(report, dict):
            raise LockValidationError("pip resolution report root must be an object")
        packages = _report_packages(report)
        for requirement in direct:
            normalized, version, _ = _parse_requirement(requirement)
            if packages.get(normalized, (None, None, None))[1] != version:
                raise LockValidationError(
                    f"pip resolution does not contain exact direct dependency {requirement}"
                )
        distribution_dir = temp_dir / "artifacts"
        requested = [f"{name}=={version}" for name, version, _ in packages.values()]
        _run(
            [
                sys.executable,
                "-m",
                "pip",
                "download",
                "--disable-pip-version-check",
                "--no-deps",
                "--dest",
                str(distribution_dir),
                *requested,
            ],
            cwd=project_dir,
        )
        downloaded_hashes = {_sha256(path) for path in distribution_dir.iterdir() if path.is_file()}
        missing = sorted(
            name for name, (_, _, digest) in packages.items() if digest not in downloaded_hashes
        )
        if missing:
            raise LockValidationError(
                f"pip download artifacts do not match the resolver report for: {', '.join(missing)}"
            )
        lines = [LOCK_HEADER, *[f"{DIRECT_PREFIX}{item}" for item in direct], ""]
        for normalized in sorted(packages):
            name, version, digest = packages[normalized]
            lines.append(f"{name}=={version} --hash=sha256:{digest}")
        lock_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    check_lock(pyproject_path, lock_path)


def export_runtime_lock(pyproject_path: Path, lock_path: Path, output_path: Path) -> None:
    """Export the lock's verified production closure without leaking dev test tooling."""

    check_lock(pyproject_path, lock_path)
    direct = runtime_dependencies(pyproject_path)
    _, complete_pins = _read_lock(lock_path)
    project_dir = pyproject_path.parent
    with tempfile.TemporaryDirectory(prefix="food-agent-runtime-lock-") as temporary:
        report_path = Path(temporary) / "runtime-resolution.json"
        _run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--dry-run",
                "--ignore-installed",
                "--report",
                str(report_path),
                "--constraint",
                str(lock_path.resolve()),
                *direct,
            ],
            cwd=project_dir,
        )
        try:
            report = json.loads(report_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise LockValidationError(f"cannot parse runtime resolution report: {error}") from error
    packages = _report_packages(report)
    selected: dict[str, tuple[str, str, set[str]]] = {}
    for normalized, (name, version, _digest) in packages.items():
        complete = complete_pins.get(normalized)
        if complete is None or complete[0] != version:
            raise LockValidationError(
                f"runtime closure is absent from verified complete lock: {name}=={version}"
            )
        selected[normalized] = (name, version, complete[1])
    lines = [LOCK_HEADER, *[f"{DIRECT_PREFIX}{item}" for item in direct], ""]
    for normalized in sorted(selected):
        name, version, hashes = selected[normalized]
        lines.append(
            f"{name}=={version}" + "".join(f" --hash=sha256:{value}" for value in sorted(hashes))
        )
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("generate", "check", "export-runtime"):
        subcommand = subparsers.add_parser(command)
        subcommand.add_argument("--pyproject", type=Path, required=True)
        subcommand.add_argument("--lock", type=Path, required=True)
        if command == "export-runtime":
            subcommand.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        if args.command == "generate":
            generate_lock(args.pyproject, args.lock)
        elif args.command == "export-runtime":
            export_runtime_lock(args.pyproject, args.lock, args.output)
        else:
            check_lock(args.pyproject, args.lock)
    except LockValidationError as error:
        print(f"LOCK GATE: FAIL: {error}", file=sys.stderr)
        return 1
    print("LOCK GATE: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
