import { execFile as execFileCallback } from 'node:child_process'
import { promisify } from 'node:util'
import { expect, test, type Page } from '@playwright/test'

import { clearMailbox, login, registerAndActivate, type E2eAccount } from './auth-helpers'

function mealCard(page: Page, mealName: '早餐' | '午餐' | '晚餐') {
  return page.getByRole('heading', { name: mealName, exact: true }).locator('xpath=ancestor::*[@data-slot="card"][1]')
}

test.describe('daily planning archive H5', () => {
  test.describe.configure({ mode: 'serial' })
  test.beforeAll(async ({ browser, request }) => {
    const context = await browser.newContext()
    const page = await context.newPage()
    const account = { email: 'plans-runtime-admin@example.test', password: 'Plans-admin-password-2026!' }
    await clearMailbox(request)
    await page.goto('/register')
    await registerAndActivate(page, request, account)
    await promisify(execFileCallback)('../backend/.venv/bin/python', ['tests/run_pg.py', '--env-file', '.env.test.example', '--', '.venv/bin/python', '-m', 'app.admin.cli', 'bootstrap', '--email', account.email, '--reason', 'Planning E2E first-admin bootstrap'], { cwd: '../backend' })
    await page.goto(`http://127.0.0.1:${process.env.E2E_RECORDS_ADMIN_FRONTEND_PORT ?? '5185'}/admin/login?returnTo=/admin/model-configs`)
    await page.getByLabel('邮箱').fill(account.email)
    await page.getByLabel('密码', { exact: true }).fill(account.password)
    await page.getByRole('button', { name: '登录后台' }).click()
    await page.getByRole('button', { name: '修改文字模型设置' }).click()
    const dialog = page.getByRole('alertdialog', { name: '确认变更未来运行配置？' })
    await dialog.getByRole('checkbox', { name: '启用新的运行配置' }).check()
    await dialog.getByLabel('单次调用上限（USD）').fill('0.02')
    await dialog.getByLabel('周期上限（USD）').fill('12')
    await dialog.getByLabel('输入价格（USD / 百万 token）').fill('0.14')
    await dialog.getByLabel('输出价格（USD / 百万 token）').fill('0.28')
    await dialog.getByLabel('变更原因').fill('为计划存档测试启用 Fake Provider')
    await dialog.getByRole('button', { name: '确认保存未来配置' }).click()
    await expect(page.getByText('当前运行策略：第 1 版')).toBeVisible()
    await context.close()
  })
  test('a real registered user generates the controlled breakfast, lunch, and dinner snapshot', async ({ page, request }) => {
    await clearMailbox(request)
    const account: E2eAccount = { email: 'daily-plans@example.test', password: 'correct-horse-battery-staple' }
    await page.goto('/register')
    await registerAndActivate(page, request, account)
    await login(page, account, '/app/plans')
    await page.getByRole('button', { name: '确认时区' }).click()

    await page.getByRole('link', { name: '去填写', exact: true }).click()
    await page.getByRole('button', { name: '填写身体资料与目标' }).click()
    await page.getByLabel('身高').fill('170')
    await page.getByRole('spinbutton', { name: '体重' }).fill('65')
    await page.getByLabel('年龄').fill('30')
    await page.getByLabel('使用女性参数').check()
    await page.getByLabel('日常活动水平').selectOption({ label: '中度活动' })
    await page.getByLabel('目标', { exact: true }).selectOption({ label: '维持体重' })
    await page.getByLabel('目标速度').selectOption('maintain')
    await page.getByRole('button', { name: '保存个人资料' }).click()
    await expect(page.getByRole('button', { name: '编辑个人资料' })).toBeVisible()
    await page.goto('/app/plans')
    await page.getByLabel('我已复核以上饮食偏好').check()
    await page.getByRole('button', { name: '生成今日餐单' }).click()

    await expect(page.getByRole('heading', { name: '今日饮食计划' })).toBeVisible()
    await expect(page.getByRole('heading', { name: '早餐' })).toBeVisible()
    await expect(page.getByRole('heading', { name: '午餐' })).toBeVisible()
    await expect(page.getByRole('heading', { name: '晚餐' })).toBeVisible()
    await expect(page.getByText(/已自动保存/)).toBeVisible()
    const savedBreakfast = await mealCard(page, '早餐').innerText()
    await page.reload()
    await expect(page.getByText(/已自动保存/)).toBeVisible()
    expect(await mealCard(page, '早餐').innerText()).toBe(savedBreakfast)
    await page.getByRole('link', { name: '历史计划', exact: true }).click()
    await page.getByRole('link', { name: /三餐计划/ }).click()
    await expect(page.getByRole('heading', { name: '计划详情', exact: true })).toBeVisible()
    await expect(mealCard(page, '早餐')).toHaveText(savedBreakfast, { useInnerText: true })
    await page.goto('/app/plans')
    const firstMeal = mealCard(page, '早餐')
    await expect(firstMeal).toContainText(/\d+g · /)
    await expect(firstMeal).toContainText(/ · /)
    await expect(firstMeal.getByLabel('烹饪与口味标签')).toContainText('清淡')
    await expect(page.locator('footer')).toHaveText('普通饮食参考，不替代医疗建议。')
    for (const width of [320, 375, 430, 768]) {
      await page.setViewportSize({ width, height: 932 })
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    }
  })

  test('a real user can adjust one owned plan without changing the other meal cards or the reading position', async ({ page, request }) => {
    await clearMailbox(request)
    const account: E2eAccount = { email: 'daily-plan-adjustment@example.test', password: 'correct-horse-battery-staple' }
    await page.goto('/register')
    await registerAndActivate(page, request, account)
    await login(page, account, '/app/plans')
    await page.getByRole('button', { name: '确认时区' }).click()

    await page.getByRole('link', { name: '去填写', exact: true }).click()
    await page.getByRole('button', { name: '填写身体资料与目标' }).click()
    await page.getByLabel('身高').fill('170')
    await page.getByRole('spinbutton', { name: '体重' }).fill('65')
    await page.getByLabel('年龄').fill('30')
    await page.getByLabel('使用女性参数').check()
    await page.getByLabel('日常活动水平').selectOption({ label: '中度活动' })
    await page.getByLabel('目标', { exact: true }).selectOption({ label: '维持体重' })
    await page.getByLabel('目标速度').selectOption('maintain')
    await page.getByRole('button', { name: '保存个人资料' }).click()
    await expect(page.getByRole('button', { name: '编辑个人资料' })).toBeVisible()
    await page.goto('/app/plans')
    await page.getByLabel('我已复核以上饮食偏好').check()
    await page.getByRole('button', { name: '生成今日餐单' }).click()
    await expect(page.getByRole('heading', { name: '今日饮食计划' })).toBeVisible()

    const breakfast = await mealCard(page, '早餐').innerText()
    const dinner = await mealCard(page, '晚餐').innerText()
    await page.getByLabel('告诉我们想换什么').fill('午餐换清淡一些')
    const submitButton = page.getByRole('button', { name: '提交调整' })
    const scrollArea = page.getByTestId('page-scroll-area')
    await scrollArea.evaluate((element) => { element.scrollTop = element.scrollHeight })
    const scrollTopBeforeAdjustment = await scrollArea.evaluate((element) => element.scrollTop)
    expect(scrollTopBeforeAdjustment).toBeGreaterThan(0)
    await submitButton.focus()
    await expect(submitButton).toBeFocused()
    await submitButton.click()

    const completionSummary = page.getByText('已更新午餐，其余餐次保持不变。')
    await expect(completionSummary).toBeVisible()
    await expect(completionSummary).toHaveAttribute('aria-live', 'polite')
    await expect(completionSummary).not.toHaveAttribute('tabindex')
    await expect(completionSummary).not.toBeFocused()
    await expect(submitButton).toBeFocused()
    // Native layout/scroll anchoring may settle by one spacing unit after the saved-version badge updates.
    // A focus jump to the result heading would move hundreds of pixels and still fails this guard.
    await expect.poll(async () => Math.abs(await scrollArea.evaluate((element) => element.scrollTop) - scrollTopBeforeAdjustment)).toBeLessThanOrEqual(8)
    await expect(mealCard(page, '午餐')).toContainText('已调整')
    expect(await mealCard(page, '早餐').innerText()).toBe(breakfast)
    expect(await mealCard(page, '晚餐').innerText()).toBe(dinner)
    await expect(page.getByText(/已自动保存.*第 2 版/)).toBeVisible()
    await page.reload()
    await expect(page.getByText(/已自动保存.*第 2 版/)).toBeVisible()
    await page.getByRole('link', { name: '历史计划', exact: true }).click()
    await page.getByRole('link', { name: /三餐计划/ }).click()
    await page.getByRole('button', { name: '上一版' }).click()
    await expect(page.getByText(/第 1 \/ 2 版/)).toBeVisible()
    await page.getByRole('button', { name: '删除这天的计划' }).click()
    await page.getByRole('button', { name: '取消', exact: true }).click()
    await page.getByRole('button', { name: '删除这天的计划' }).click()
    await page.getByRole('button', { name: '确认删除', exact: true }).click()
    await expect(page.getByText(/还没有保存的计划/)).toBeVisible()
    await page.goto('/app/plans')
    await expect(page.getByRole('button', { name: '生成今日餐单' })).toBeVisible()
    await expect(page.getByRole('heading', { name: '今日饮食计划' })).toHaveCount(0)

  })
})
