import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '@/auth/useAuth'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { deleteMealRecord, getMealRecord, updateMealRecord } from '../api/client'
import { toLocalDateTimeInput } from '../format'

export function MealRecordEditPage() { const { recordId = '' } = useParams(); const navigate = useNavigate(); const { request } = useAuth(); const [value, setValue] = useState(''); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); useEffect(() => { void getMealRecord(request, recordId).then((record) => setValue(toLocalDateTimeInput(record.consumed_at))).catch(() => setError('无法加载记录。')) }, [recordId, request]); async function save() { setSaving(true); try { await updateMealRecord(request, recordId, new Date(value).toISOString()); navigate(`/app/records/${recordId}`, { replace: true }) } catch { setError('保存失败，请填写过去的用餐时间。') } finally { setSaving(false) } } async function remove() { setSaving(true); try { await deleteMealRecord(request, recordId); navigate('/app/records', { replace: true, state: { notice: '已删除' } }) } catch { setError('删除失败，请稍后重试。') } finally { setSaving(false); setOpen(false) } } return <section className="space-y-4"><div><h1 className="text-[28px] font-bold leading-9 tracking-tight">编辑餐食</h1><p className="mt-2 text-sm text-muted-foreground">修改用餐时间不会重算已保存的营养快照。</p></div><div className="space-y-2"><Label htmlFor="consumed-at">用餐时间</Label><Input className="h-11" id="consumed-at" max={toLocalDateTimeInput(new Date().toISOString())} onChange={(event) => setValue(event.target.value)} type="datetime-local" value={value} /></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}<Button className="h-11 w-full" disabled={saving || !value} onClick={() => void save()} type="button">{saving ? '正在保存…' : '保存修改'}</Button><div className="border-t border-border pt-4"><h2 className="font-semibold text-destructive">危险操作</h2><p className="mt-1 text-sm text-muted-foreground">删除后，这条餐食记录将无法恢复。</p><Button className="mt-3 h-11 w-full" disabled={saving} onClick={() => setOpen(true)} type="button" variant="destructive">删除餐食记录</Button></div><AlertDialog onOpenChange={setOpen} open={open}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这条餐食记录？</AlertDialogTitle><AlertDialogDescription>删除后，这条记录将无法恢复。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={() => void remove()} variant="destructive">确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section> }
