import { mealSlotLabels } from '../api/mealMetadata'
import { Pencil } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '@/auth/useAuth'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { getMealRecord, type MealRecord } from '../api/client'
import { formatNutrition } from '../format'

export function MealRecordDetailPage() { const { recordId = '' } = useParams(); const { request } = useAuth(); const [record, setRecord] = useState<MealRecord>(); const [error, setError] = useState(''); useEffect(() => { void getMealRecord(request, recordId).then(setRecord).catch(() => setError('这条记录不存在或无法访问。')) }, [recordId, request]); if (error) return <Alert variant="destructive"><AlertTitle>无法查看记录</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>; if (!record) return <p className="text-sm text-muted-foreground">正在加载记录…</p>; return <section className="space-y-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">{record.meal_slot ? mealSlotLabels[record.meal_slot] : '未分类'} · {new Date(record.consumed_at).toLocaleString('zh-CN')}</p></div><Link aria-label="编辑餐食记录" className="inline-flex size-11 items-center justify-center rounded-lg border border-input" to={`/app/records/${record.id}/edit`}><Pencil className="size-5" /></Link></div><Card><CardHeader><CardTitle className="tabular-nums text-2xl font-bold leading-8">合计 {formatNutrition(record.energy_kcal)} kcal</CardTitle></CardHeader><CardContent className="space-y-3">{record.items.map((item) => <div className="space-y-1 rounded-md bg-muted/60 p-3" key={item.id}><p className="break-words text-[15px] font-semibold leading-6">{item.display_name}</p><p className="tabular-nums text-sm text-muted-foreground">{formatNutrition(item.grams)}g · {formatNutrition(item.energy_kcal)} kcal</p><p className="tabular-nums text-[13px] text-muted-foreground">蛋白质 {formatNutrition(item.protein_g)}g · 脂肪 {formatNutrition(item.fat_g)}g · 碳水 {formatNutrition(item.carbohydrate_g)}g</p></div>)}</CardContent></Card><p className="break-words text-[13px] leading-5 text-muted-foreground">目录版本：{record.nutrition_catalog_version} · 计算版本：{record.calculation_version}</p><p className="break-words text-[13px] leading-5 text-muted-foreground">更新于 {new Date(record.updated_at).toLocaleString('zh-CN')}</p></section> }
