/* This file is generated by generate-contracts.mjs. Do not edit it. */
import { requestWithAccess } from '@/auth/api'
import type * as Contract from './schemas.generated'

export async function createAgentThread(accessToken: string, payload: Contract.AgentThreadCreateRequest): Promise<Response> {
  return requestWithAccess(`/agent/threads`, accessToken, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })
}
export type createAgentThreadResponse = Contract.AgentThreadSnapshot

export async function getAgentThread(accessToken: string, thread_id: string): Promise<Response> {
  return requestWithAccess(`/agent/threads/${encodeURIComponent(thread_id)}`, accessToken, { method: 'GET' })
}
export type getAgentThreadResponse = Contract.AgentThreadSnapshot

export async function deleteAgentThread(accessToken: string, thread_id: string): Promise<Response> {
  return requestWithAccess(`/agent/threads/${encodeURIComponent(thread_id)}`, accessToken, { method: 'DELETE' })
}
export type deleteAgentThreadResponse = Contract.AgentDeletionAcceptedResponse

export async function streamAgentEvents(accessToken: string, thread_id: string): Promise<Response> {
  return requestWithAccess(`/agent/threads/${encodeURIComponent(thread_id)}/events`, accessToken, { method: 'GET' })
}
export type streamAgentEventsResponse = unknown

export async function submitAgentInput(accessToken: string, thread_id: string, payload: Contract.AgentInputRequest): Promise<Response> {
  return requestWithAccess(`/agent/threads/${encodeURIComponent(thread_id)}/input`, accessToken, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })
}
export type submitAgentInputResponse = Contract.AgentCommandAcceptedResponse

export async function retryAgentRun(accessToken: string, thread_id: string): Promise<Response> {
  return requestWithAccess(`/agent/threads/${encodeURIComponent(thread_id)}/retry`, accessToken, { method: 'POST' })
}
export type retryAgentRunResponse = Contract.AgentCommandAcceptedResponse

