/* This file is generated by generate-contracts.mjs. Do not edit it. */
import type * as Contract from './schemas.generated'

export type AgentApiRequest = (path: string, init?: RequestInit) => Promise<Response>

export async function createAgentThread(request: AgentApiRequest, payload: Contract.AgentThreadCreateRequest): Promise<Response> {
  return request(`/agent/threads`, { method: 'POST', headers: { 'Content-Type': 'application/json', Prefer: 'respond-async' }, body: JSON.stringify(payload) })
}
export type createAgentThreadResponse = Contract.AgentThreadSnapshot

export async function getAgentThread(request: AgentApiRequest, thread_id: string): Promise<Response> {
  return request(`/agent/threads/${encodeURIComponent(thread_id)}`, { method: 'GET' })
}
export type getAgentThreadResponse = Contract.AgentThreadSnapshot

export async function deleteAgentThread(request: AgentApiRequest, thread_id: string): Promise<Response> {
  return request(`/agent/threads/${encodeURIComponent(thread_id)}`, { method: 'DELETE' })
}
export type deleteAgentThreadResponse = Contract.AgentDeletionAcceptedResponse

export async function streamAgentEvents(request: AgentApiRequest, thread_id: string): Promise<Response> {
  return request(`/agent/threads/${encodeURIComponent(thread_id)}/events`, { method: 'GET' })
}
export type streamAgentEventsResponse = unknown

export async function uploadAgentMealImage(request: AgentApiRequest, thread_id: string, image: File, commandKey: string): Promise<Response> {
  return request(`/agent/threads/${encodeURIComponent(thread_id)}/images`, { method: 'POST', headers: { 'Idempotency-Key': commandKey, Prefer: 'respond-async' }, body: (() => { const form = new FormData(); form.append('image', image); return form })() })
}
export type uploadAgentMealImageResponse = Contract.AgentImageAcceptedResponse

export async function submitAgentInput(request: AgentApiRequest, thread_id: string, payload: Contract.AgentInputRequest): Promise<Response> {
  return request(`/agent/threads/${encodeURIComponent(thread_id)}/input`, { method: 'POST', headers: { 'Content-Type': 'application/json', Prefer: 'respond-async' }, body: JSON.stringify(payload) })
}
export type submitAgentInputResponse = Contract.AgentCommandAcceptedResponse

export async function retryAgentRun(request: AgentApiRequest, thread_id: string): Promise<Response> {
  return request(`/agent/threads/${encodeURIComponent(thread_id)}/retry`, { method: 'POST' })
}
export type retryAgentRunResponse = Contract.AgentCommandAcceptedResponse

export async function createDietPlanningThread(request: AgentApiRequest, payload: Contract.DietPlanningStartCommand): Promise<Response> {
  return request(`/agent/threads/diet-planning`, { method: 'POST', headers: { 'Content-Type': 'application/json', Prefer: 'respond-async' }, body: JSON.stringify(payload) })
}
export type createDietPlanningThreadResponse = Contract.AgentThreadSnapshot

export async function createAgentImageThread(request: AgentApiRequest): Promise<Response> {
  return request(`/agent/threads/image`, { method: 'POST' })
}
export type createAgentImageThreadResponse = Contract.AgentThreadSnapshot
