/* This file is generated by generate-contracts.mjs. Do not edit it. */
import { z } from 'zod'

export const activityLevelSchema = z.enum(["sedentary", "light", "moderate", "high", "very_high"])
export type ActivityLevel = z.infer<typeof activityLevelSchema>

export const agentCommandAcceptedResponseSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema),
}).strict()
export type AgentCommandAcceptedResponse = z.infer<typeof agentCommandAcceptedResponseSchema>

export const agentDeletionAcceptedResponseSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema).default("deletion_pending").optional(),
  "due_at": z.string(),
}).strict()
export type AgentDeletionAcceptedResponse = z.infer<typeof agentDeletionAcceptedResponseSchema>

export const agentErrorDetailSchema = z.object({
  "code": z.string(),
  "message": z.string(),
  "request_id": z.string().uuid(),
}).strict()
export type AgentErrorDetail = z.infer<typeof agentErrorDetailSchema>

export const agentErrorResponseSchema = z.object({
  "error": z.lazy(() => agentErrorDetailSchema),
}).strict()
export type AgentErrorResponse = z.infer<typeof agentErrorResponseSchema>

export const agentImageAcceptedResponseSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema),
  "image_id": z.string().uuid(),
}).strict()
export type AgentImageAcceptedResponse = z.infer<typeof agentImageAcceptedResponseSchema>

export const agentInputKindSchema = z.enum(["description"])
export type AgentInputKind = z.infer<typeof agentInputKindSchema>

export const agentInputRequestSchema = z.object({
  "kind": z.lazy(() => agentInputKindSchema),
  "text": z.string().min(1).max(4000),
}).strict()
export type AgentInputRequest = z.infer<typeof agentInputRequestSchema>

export const agentThreadCreateRequestSchema = z.object({
  "input_text": z.string().min(1).max(4000),
}).strict()
export type AgentThreadCreateRequest = z.infer<typeof agentThreadCreateRequestSchema>

export const agentThreadSnapshotSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema),
  "revision": z.number().int().min(0),
  "report": z.unknown().optional(),
  "recovery_code": z.unknown().optional(),
}).strict()
export type AgentThreadSnapshot = z.infer<typeof agentThreadSnapshotSchema>

export const agentThreadStatusSchema = z.enum(["waiting", "partial", "completed", "retryable", "terminal", "deletion_pending"])
export type AgentThreadStatus = z.infer<typeof agentThreadStatusSchema>

export const body_uploadAgentMealImageSchema = z.object({
  "image": z.string(),
}).passthrough()
export type Body_uploadAgentMealImage = z.infer<typeof body_uploadAgentMealImageSchema>

export const dietPlanningStartCommandSchema = z.object({
  "profile": z.lazy(() => planningProfileInputSchema),
  "preferences": z.lazy(() => preferenceReviewSchema),
  "save_profile": z.boolean().default(false).optional(),
}).strict()
export type DietPlanningStartCommand = z.infer<typeof dietPlanningStartCommandSchema>

export const formulaVariantSchema = z.enum(["mifflin_st_jeor_male", "mifflin_st_jeor_female"])
export type FormulaVariant = z.infer<typeof formulaVariantSchema>

export const httpValidationErrorSchema = z.object({
  "detail": z.array(z.lazy(() => validationErrorSchema)).optional(),
}).passthrough()
export type HTTPValidationError = z.infer<typeof httpValidationErrorSchema>

export const planningGoalSchema = z.enum(["maintain", "loss", "gain"])
export type PlanningGoal = z.infer<typeof planningGoalSchema>

export const planningProfileInputSchema = z.object({
  "height_cm": z.unknown().optional(),
  "weight_kg": z.unknown().optional(),
  "age_years": z.unknown().optional(),
  "formula_variant": z.unknown().optional(),
  "activity_level": z.unknown().optional(),
  "goal": z.unknown().optional(),
  "goal_speed": z.unknown().optional(),
  "is_pregnant_or_breastfeeding": z.boolean().default(false).optional(),
  "has_disease_or_treatment": z.boolean().default(false).optional(),
  "uses_medication": z.boolean().default(false).optional(),
  "has_eating_disorder_or_self_harm_risk": z.boolean().default(false).optional(),
  "has_extreme_weight_control_goal": z.boolean().default(false).optional(),
}).strict()
export type PlanningProfileInput = z.infer<typeof planningProfileInputSchema>

export const preferenceReviewSchema = z.object({
  "confirmed": z.boolean(),
  "exclusions": z.array(z.string()).default([]).optional(),
  "taste_preferences": z.array(z.string()).default([]).optional(),
}).strict()
export type PreferenceReview = z.infer<typeof preferenceReviewSchema>

export const validationErrorSchema = z.object({
  "loc": z.array(z.unknown()),
  "msg": z.string(),
  "type": z.string(),
  "input": z.unknown().optional(),
  "ctx": z.object({

}).passthrough().optional(),
}).passthrough()
export type ValidationError = z.infer<typeof validationErrorSchema>

