/* This file is generated by generate-contracts.mjs. Do not edit it. */
import { z } from 'zod'

export const agentCommandAcceptedResponseSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema),
}).strict()
export type AgentCommandAcceptedResponse = z.infer<typeof agentCommandAcceptedResponseSchema>

export const agentDeletionAcceptedResponseSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema).default("deletion_pending").optional(),
  "due_at": z.string(),
}).strict()
export type AgentDeletionAcceptedResponse = z.infer<typeof agentDeletionAcceptedResponseSchema>

export const agentErrorDetailSchema = z.object({
  "code": z.string(),
  "message": z.string(),
  "request_id": z.string().uuid(),
}).strict()
export type AgentErrorDetail = z.infer<typeof agentErrorDetailSchema>

export const agentErrorResponseSchema = z.object({
  "error": z.lazy(() => agentErrorDetailSchema),
}).strict()
export type AgentErrorResponse = z.infer<typeof agentErrorResponseSchema>

export const agentImageAcceptedResponseSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema),
  "image_id": z.string().uuid(),
}).strict()
export type AgentImageAcceptedResponse = z.infer<typeof agentImageAcceptedResponseSchema>

export const agentInputKindSchema = z.enum(["description"])
export type AgentInputKind = z.infer<typeof agentInputKindSchema>

export const agentInputRequestSchema = z.object({
  "kind": z.lazy(() => agentInputKindSchema),
  "text": z.string().min(1).max(4000),
}).strict()
export type AgentInputRequest = z.infer<typeof agentInputRequestSchema>

export const agentThreadCreateRequestSchema = z.object({
  "input_text": z.string().min(1).max(4000),
}).strict()
export type AgentThreadCreateRequest = z.infer<typeof agentThreadCreateRequestSchema>

export const agentThreadSnapshotSchema = z.object({
  "thread_id": z.string().uuid(),
  "status": z.lazy(() => agentThreadStatusSchema),
  "revision": z.number().int().min(0),
  "report": z.unknown().optional(),
  "recovery_code": z.unknown().optional(),
}).strict()
export type AgentThreadSnapshot = z.infer<typeof agentThreadSnapshotSchema>

export const agentThreadStatusSchema = z.enum(["waiting", "partial", "completed", "retryable", "terminal", "deletion_pending"])
export type AgentThreadStatus = z.infer<typeof agentThreadStatusSchema>

export const body_uploadAgentMealImageSchema = z.object({
  "image": z.string(),
}).passthrough()
export type Body_uploadAgentMealImage = z.infer<typeof body_uploadAgentMealImageSchema>

export const httpValidationErrorSchema = z.object({
  "detail": z.array(z.lazy(() => validationErrorSchema)).optional(),
}).passthrough()
export type HTTPValidationError = z.infer<typeof httpValidationErrorSchema>

export const validationErrorSchema = z.object({
  "loc": z.array(z.unknown()),
  "msg": z.string(),
  "type": z.string(),
  "input": z.unknown().optional(),
  "ctx": z.object({

}).passthrough().optional(),
}).passthrough()
export type ValidationError = z.infer<typeof validationErrorSchema>

