"""Minimal Provider contract: only a canonical preference statement crosses the boundary."""

from __future__ import annotations

import uuid
from datetime import datetime
from dataclasses import dataclass
from typing import Protocol

from app.records.models import MemoryDeletionOutbox, PreferenceMemoryLedger


@dataclass(frozen=True, slots=True)
class MemorySearchHit:
    external_id: str
    canonical_text: str


class MemoryProvider(Protocol):
    def create(self, *, user_id: uuid.UUID, category: str, canonical_text: str) -> str: ...
    def update(self, *, user_id: uuid.UUID, external_id: str, category: str, canonical_text: str) -> None: ...
    def delete(self, *, user_id: uuid.UUID, external_id: str) -> None: ...
    def search(self, *, user_id: uuid.UUID, query: str, limit: int) -> list[MemorySearchHit]: ...


class MemoryLedgerRepository(Protocol):
    def add_ledger(self, ledger: PreferenceMemoryLedger) -> PreferenceMemoryLedger: ...
    def get_active_for_user(self, *, ledger_id: uuid.UUID, user_id: uuid.UUID, for_update: bool = False) -> PreferenceMemoryLedger | None: ...
    def get_for_user(self, *, ledger_id: uuid.UUID, user_id: uuid.UUID) -> PreferenceMemoryLedger | None: ...
    def list_active_for_user(self, *, user_id: uuid.UUID) -> list[PreferenceMemoryLedger]: ...
    def add_outbox(self, outbox: MemoryDeletionOutbox) -> MemoryDeletionOutbox: ...
    def list_due_outbox(self, *, due_at: datetime) -> list[MemoryDeletionOutbox]: ...
