"""Narrow persistence boundary for confirmed meal records."""

from __future__ import annotations

import uuid
from typing import Protocol

from app.agent.models import AgentEvent, AgentRun
from app.records.models import DashboardTimezoneBackfillAudit, DashboardTimezonePreference, MealRecord


class MealRecordRepository(Protocol):
    def get_completed_run_for_thread_for_user(self, *, thread_id: uuid.UUID, user_id: uuid.UUID, for_update: bool = False) -> AgentRun | None: ...
    def get_completed_report_for_run_for_user(self, *, run_id: uuid.UUID, user_id: uuid.UUID) -> AgentEvent | None: ...
    def get_record_for_command_for_user(self, *, command_key: str, user_id: uuid.UUID, include_deleted: bool = False) -> MealRecord | None: ...
    def get_record_for_source_run_for_user(self, *, source_run_id: uuid.UUID, user_id: uuid.UUID, include_deleted: bool = False) -> MealRecord | None: ...
    def add_record(self, record: MealRecord) -> MealRecord: ...
    def get_record_for_user(self, *, record_id: uuid.UUID, user_id: uuid.UUID, for_update: bool = False) -> MealRecord | None: ...
    def list_records_for_user(self, *, user_id: uuid.UUID) -> list[MealRecord]: ...
    def get_dashboard_time_zone_preference_for_user(self, *, user_id: uuid.UUID, for_update: bool = False) -> DashboardTimezonePreference | None: ...
    def add_dashboard_time_zone_preference(self, preference: DashboardTimezonePreference) -> DashboardTimezonePreference: ...
    def list_records_without_local_date_for_user(self, *, user_id: uuid.UUID) -> list[MealRecord]: ...
    def add_timezone_backfill_audit(self, audit: DashboardTimezoneBackfillAudit) -> DashboardTimezoneBackfillAudit: ...
