"""Archive transaction ports; the graph never receives database access."""

import uuid
from datetime import date, datetime
from typing import Protocol

from app.planning.archive_schemas import PlanArchiveWrite
from app.planning.models import DietPlan, DietPlanVersion


class PlanArchiveWriter(Protocol):
    def check_admission(self, *, user_id: uuid.UUID, thread_id: uuid.UUID) -> None: ...
    def record_completion(self, command: PlanArchiveWrite) -> None: ...


class PlanArchiveRepository(Protocol):
    def lock_owner(self, user_id: uuid.UUID) -> None: ...
    def time_zone(self, user_id: uuid.UUID) -> str | None: ...
    def by_id(self, user_id: uuid.UUID, plan_id: uuid.UUID) -> DietPlan | None: ...
    def latest_deletion(self, user_id: uuid.UUID, day: date) -> datetime | None: ...
    def by_date(self, user_id: uuid.UUID, day: date) -> DietPlan | None: ...
    def by_thread(
        self, user_id: uuid.UUID, thread_id: uuid.UUID
    ) -> DietPlan | None: ...
    def by_run(
        self, user_id: uuid.UUID, run_id: uuid.UUID
    ) -> DietPlanVersion | None: ...
    def version(
        self, user_id: uuid.UUID, plan_id: uuid.UUID, number: int
    ) -> DietPlanVersion | None: ...
    def history(
        self, user_id: uuid.UUID, before: date | None, limit: int
    ) -> list[DietPlan]: ...
    def add_plan(self, plan: DietPlan) -> None: ...
    def add_version(self, version: DietPlanVersion) -> None: ...
    def flush(self) -> None: ...
    def erase_snapshots(self, user_id: uuid.UUID, plan_id: uuid.UUID) -> None: ...
    def resumable(self, user_id: uuid.UUID, thread_id: uuid.UUID) -> bool: ...
    def recipe_versions(self, ids: tuple[uuid.UUID, ...]) -> list[dict[str, str]]: ...
